# Generated by Django 4.1.3 on 2024-05-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(max_length=70)),
                ('token_address', models.CharField(max_length=42)),
                ('sender_address', models.CharField(max_length=42)),
                ('receiver_address', models.CharField(max_length=42)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('origin_chain', models.CharField(max_length=10)),
                ('destination_chain', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
