# Generated by Django 4.1.3 on 2024-05-12 10:48

from django.db import migrations, models
import main.apps.profile.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=main.apps.profile.models.models.user_profile_img_path),
        ),
    ]
